# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'speedtest.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(811, 441)
        Form.setMinimumSize(QtCore.QSize(811, 441))
        Form.setMaximumSize(QtCore.QSize(811, 441))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/AYTEN/Desktop/speedtest/speed.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(40, 30, 731, 271))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setObjectName("frame")
        self.download_resim = QtWidgets.QLabel(self.frame)
        self.download_resim.setGeometry(QtCore.QRect(30, 10, 651, 251))
        self.download_resim.setText("")
        self.download_resim.setPixmap(QtGui.QPixmap("C:/Users/AYTEN/Desktop/speedtest/speed_Bilgisi.png"))
        self.download_resim.setObjectName("download_resim")
        self.download_speed = QtWidgets.QLabel(self.frame)
        self.download_speed.setGeometry(QtCore.QRect(70, 170, 119, 19))
        self.download_speed.setObjectName("download_speed")
        self.upload_speed = QtWidgets.QLabel(self.frame)
        self.upload_speed.setGeometry(QtCore.QRect(310, 170, 98, 19))
        self.upload_speed.setObjectName("upload_speed")
        self.ping = QtWidgets.QLabel(self.frame)
        self.ping.setGeometry(QtCore.QRect(580, 170, 68, 19))
        self.ping.setObjectName("ping")
        self.sonuc_resim_1 = QtWidgets.QLabel(self.frame)
        self.sonuc_resim_1.setGeometry(QtCore.QRect(50, 220, 161, 21))
        self.sonuc_resim_1.setText("")
        self.sonuc_resim_1.setPixmap(QtGui.QPixmap("C:/Users/AYTEN/Desktop/speedtest/sncc.png"))
        self.sonuc_resim_1.setObjectName("sonuc_resim_1")
        self.sonuc_resim_2 = QtWidgets.QLabel(self.frame)
        self.sonuc_resim_2.setGeometry(QtCore.QRect(290, 220, 141, 19))
        self.sonuc_resim_2.setText("")
        self.sonuc_resim_2.setPixmap(QtGui.QPixmap("C:/Users/AYTEN/Desktop/speedtest/sncc.png"))
        self.sonuc_resim_2.setObjectName("sonuc_resim_2")
        self.sonuc_resim_3 = QtWidgets.QLabel(self.frame)
        self.sonuc_resim_3.setGeometry(QtCore.QRect(530, 220, 68, 19))
        self.sonuc_resim_3.setText("")
        self.sonuc_resim_3.setPixmap(QtGui.QPixmap("C:/Users/AYTEN/Desktop/speedtest/sncc.png"))
        self.sonuc_resim_3.setObjectName("sonuc_resim_3")
        self.sonuc_yazi_1 = QtWidgets.QLabel(self.frame)
        self.sonuc_yazi_1.setGeometry(QtCore.QRect(120, 220, 171, 19))
        self.sonuc_yazi_1.setObjectName("sonuc_yazi_1")
        self.sonuc_yazi_2 = QtWidgets.QLabel(self.frame)
        self.sonuc_yazi_2.setGeometry(QtCore.QRect(360, 220, 171, 19))
        self.sonuc_yazi_2.setObjectName("sonuc_yazi_2")
        self.sonuc_yazi_3 = QtWidgets.QLabel(self.frame)
        self.sonuc_yazi_3.setGeometry(QtCore.QRect(600, 220, 171, 19))
        self.sonuc_yazi_3.setObjectName("sonuc_yazi_3")
        self.sonuc_resim_1.raise_()
        self.sonuc_resim_3.raise_()
        self.sonuc_resim_2.raise_()
        self.sonuc_yazi_3.raise_()
        self.download_resim.raise_()
        self.ping.raise_()
        self.download_speed.raise_()
        self.upload_speed.raise_()
        self.sonuc_yazi_1.raise_()
        self.sonuc_yazi_2.raise_()
        self.hizihesapla = QtWidgets.QPushButton(Form)
        self.hizihesapla.setGeometry(QtCore.QRect(50, 310, 231, 41))
        self.hizihesapla.setObjectName("hizihesapla")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(40, 300, 731, 111))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.bilinmesi_gerekenler = QtWidgets.QPushButton(self.frame_2)
        self.bilinmesi_gerekenler.setGeometry(QtCore.QRect(10, 60, 231, 41))
        self.bilinmesi_gerekenler.setObjectName("bilinmesi_gerekenler")
        self.listWidget = QtWidgets.QListWidget(self.frame_2)
        self.listWidget.setGeometry(QtCore.QRect(250, 10, 471, 91))
        self.listWidget.setObjectName("listWidget")
        self.frame.raise_()
        self.frame_2.raise_()
        self.hizihesapla.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SpeedTest v1 - Cankat Özçakır"))
        self.download_speed.setText(_translate("Form", "Download Speed"))
        self.upload_speed.setText(_translate("Form", "Upload Speed"))
        self.ping.setText(_translate("Form", "Ping"))
        self.sonuc_yazi_1.setText(_translate("Form", "0"))
        self.sonuc_yazi_2.setText(_translate("Form", "0"))
        self.sonuc_yazi_3.setText(_translate("Form", "0"))
        self.hizihesapla.setText(_translate("Form", "Hesapla!"))
        self.bilinmesi_gerekenler.setText(_translate("Form", "Bilinmesi Gerekenler"))

